/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IBSVS"
 * 	found in "svs.asn"
 * 	`asn1c -fbless-SIZE`
 */

#ifndef	_CertificateRevocationLists_H_
#define	_CertificateRevocationLists_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateList;

/* CertificateRevocationLists */
typedef struct CertificateRevocationLists {
	A_SET_OF(struct CertificateList) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateRevocationLists_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateRevocationLists;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateRevocationList.h"

#endif	/* _CertificateRevocationLists_H_ */
#include <asn_internal.h>
