/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IBSVS"
 * 	found in "svs.asn"
 * 	`asn1c -fbless-SIZE`
 */

#ifndef	_CertificateRevocationList_H_
#define	_CertificateRevocationList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertificateList.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateRevocationList */
typedef CertificateList_t	 CertificateRevocationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateRevocationList;
asn_struct_free_f CertificateRevocationList_free;
asn_struct_print_f CertificateRevocationList_print;
asn_constr_check_f CertificateRevocationList_constraint;
ber_type_decoder_f CertificateRevocationList_decode_ber;
der_type_encoder_f CertificateRevocationList_encode_der;
xer_type_decoder_f CertificateRevocationList_decode_xer;
xer_type_encoder_f CertificateRevocationList_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateRevocationList_H_ */
#include <asn_internal.h>
