/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IBSVS"
 * 	found in "svs.asn"
 * 	`asn1c -fbless-SIZE`
 */

#ifndef	_CreateTimeStampResponseResp_H_
#define	_CreateTimeStampResponseResp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateTimeStampResponseResp */
typedef struct CreateTimeStampResponseResp {
	long	 respValue;
	OCTET_STRING_t	*outData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateTimeStampResponseResp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateTimeStampResponseResp;

#ifdef __cplusplus
}
#endif

#endif	/* _CreateTimeStampResponseResp_H_ */
#include <asn_internal.h>
