/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IBSVS"
 * 	found in "svs.asn"
 * 	`asn1c -fbless-SIZE`
 */

#ifndef	_CreateTimeStampRequestReq_H_
#define	_CreateTimeStampRequestReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateTimeStampRequestReq */
typedef struct CreateTimeStampRequestReq {
	OCTET_STRING_t	 inData;
	long	 hashMethod;
	BOOLEAN_t	 certReq;
	BOOLEAN_t	 nonce;
	OCTET_STRING_t	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateTimeStampRequestReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateTimeStampRequestReq;

#ifdef __cplusplus
}
#endif

#endif	/* _CreateTimeStampRequestReq_H_ */
#include <asn_internal.h>
