/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IBSVS"
 * 	found in "svs.asn"
 * 	`asn1c -fbless-SIZE`
 */

#ifndef	_DigestEncryptionAlgorithmIdentifier_H_
#define	_DigestEncryptionAlgorithmIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DigestEncryptionAlgorithmIdentifier */
typedef AlgorithmIdentifier_t	 DigestEncryptionAlgorithmIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DigestEncryptionAlgorithmIdentifier;
asn_struct_free_f DigestEncryptionAlgorithmIdentifier_free;
asn_struct_print_f DigestEncryptionAlgorithmIdentifier_print;
asn_constr_check_f DigestEncryptionAlgorithmIdentifier_constraint;
ber_type_decoder_f DigestEncryptionAlgorithmIdentifier_decode_ber;
der_type_encoder_f DigestEncryptionAlgorithmIdentifier_encode_der;
xer_type_decoder_f DigestEncryptionAlgorithmIdentifier_decode_xer;
xer_type_encoder_f DigestEncryptionAlgorithmIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DigestEncryptionAlgorithmIdentifier_H_ */
#include <asn_internal.h>
